chat-url = "http://127.0.0.1:1234/v1/"
chat-model = "qwen2.5-7b-instruct-1m"

sd-url = "http://127.0.0.1:7860/sdapi/v1/"
sd-model = "dreamshaper_8_93211"
sd-prompt = "RAW photo,8k uhd,dslr,high quality"
sd-negative-prompt = "nsfw,underexposed,underexposure,overexposure,overexposed,canvas frame,cartoon,3d,3d render,CGI,computer graphics"
