"""baseline: mirrors the pre-existing Drizzle schema exactly

Hand-authored (not autogenerated) so it matches `src/lib/server/db/schema.ts` precisely. On a
pre-existing `local.db` this migration is never actually executed — `app.db.migrate` stamps such
databases to this revision instead (see that module's docstring). It only runs for real against a
fresh/empty database (new dev setup, CI, tests).

Revision ID: 0001
Revises:
Create Date: 2026-09-02

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "creators",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("age", sa.Integer, nullable=False, server_default="25"),
        sa.Column("pronouns", sa.Text, nullable=False, server_default="they/them"),
        sa.Column("bio", sa.Text),
        sa.Column("location", sa.JSON),
        sa.Column("occupation", sa.Text),
        sa.Column("interests", sa.JSON),
        sa.Column("relationship_status", sa.Text),
        sa.Column("password_hash", sa.Text, nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("age", sa.Integer, nullable=False),
        sa.Column("pronouns", sa.Text, nullable=False),
        sa.Column("bio", sa.Text),
        sa.Column("location", sa.JSON),
        sa.Column("occupation", sa.Text),
        sa.Column("interests", sa.JSON),
        sa.Column("personality_traits", sa.Text),
        sa.Column("relationship_status", sa.Text),
        sa.Column("writing_style", sa.Text),
        sa.Column("backstory", sa.Text),
        sa.Column("additional_prompt", sa.Text, nullable=False, server_default=""),
        sa.Column("appearance", sa.Text),
        sa.Column("memory", sa.Text),
        sa.Column("image_id", sa.Integer, sa.ForeignKey("images.id")),
        sa.Column(
            "creator_id",
            sa.Integer,
            sa.ForeignKey("creators.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scenario", sa.Text),
        sa.Column("first_mes", sa.Text),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
    )

    op.create_table(
        "images",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("params", sa.JSON),
        sa.Column("type", sa.Text, nullable=False, server_default="image/webp"),
        sa.Column("data", sa.LargeBinary, nullable=False),
        sa.Column("blur", sa.Boolean, nullable=False, server_default=sa.false()),
    )

    op.create_table(
        "media",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("params", sa.JSON),
        sa.Column("type", sa.Text, nullable=False),
        sa.Column("data", sa.LargeBinary, nullable=False),
    )

    op.create_table(
        "posts",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("image_id", sa.Integer, sa.ForeignKey("images.id", ondelete="SET NULL")),
        sa.Column("media_id", sa.Integer, sa.ForeignKey("media.id", ondelete="SET NULL")),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("body_en", sa.Text),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "post_id", sa.Integer, sa.ForeignKey("posts.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE")),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("body_en", sa.Text),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    op.create_table(
        "chats",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("image_id", sa.Integer, sa.ForeignKey("images.id", ondelete="SET NULL")),
        sa.Column("role", sa.Text, nullable=False),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("body_en", sa.Text),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    op.create_table(
        "image_generation_jobs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("post_id", sa.Integer, sa.ForeignKey("posts.id", ondelete="CASCADE")),
        sa.Column("image_id", sa.Integer, sa.ForeignKey("images.id", ondelete="SET NULL")),
        sa.Column("provider", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False, server_default="queued"),
        sa.Column("target", sa.Text, nullable=False),
        sa.Column("image_style", sa.Text, nullable=False),
        sa.Column("prompt", sa.Text, nullable=False),
        sa.Column("negative_prompt", sa.Text),
        sa.Column("width", sa.Integer, nullable=False),
        sa.Column("height", sa.Integer, nullable=False),
        sa.Column("include_default_prompt", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("set_as_user_image", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("provider_job_id", sa.Text),
        sa.Column("provider_metadata", sa.JSON),
        sa.Column("error", sa.Text),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("started_at", sa.Text),
        sa.Column("completed_at", sa.Text),
    )

    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "user_id", sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "related_user_id",
            sa.Integer,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("relationship_type", sa.Text),
        sa.Column("description", sa.Text),
        sa.Column("created_at", sa.Text, server_default=sa.text("CURRENT_TIMESTAMP")),
    )


def downgrade() -> None:
    op.drop_table("relationships")
    op.drop_table("image_generation_jobs")
    op.drop_table("chats")
    op.drop_table("comments")
    op.drop_table("posts")
    op.drop_table("media")
    op.drop_table("images")
    op.drop_table("users")
    op.drop_table("creators")
